pipx install of biobricks does not enforce python version, and it is incompatible with python 3.8

biobricks configure

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\kyuha\.local\bin\biobricks.exe\__main__.py", line 4, in <module>
  File "C:\Users\kyuha\pipx\venvs\biobricks\lib\site-packages\biobricks\__init__.py", line 2, in <module>
    from .brick import Brick
  File "C:\Users\kyuha\pipx\venvs\biobricks\lib\site-packages\biobricks\brick.py", line 8, in <module>
    from .dvc_fetcher import DVCFetcher
  File "C:\Users\kyuha\pipx\venvs\biobricks\lib\site-packages\biobricks\dvc_fetcher.py", line 102, in <module>
    class DVCFetcher:
  File "C:\Users\kyuha\pipx\venvs\biobricks\lib\site-packages\biobricks\dvc_fetcher.py", line 115, in DVCFetcher
    def _expand_outdir(self, remote_url, path : Path) -> list[dict]:
TypeError: 'type' object is not subscriptable
